### ISSUE TITLE
A separate tab for the updatable entries

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Icon-Request-Dashboard#2]
Updatable entries are put in a text file inside the /scripts folder. It might be nice to have them displayed on the dashboard too.

Some extra enhancement options would be:
- sorting for updatable.txt 
- select all entries, or checkboxes to select multiple ones?  

suggestions are welcome

**Comment by Kaiserdragon2** [comment]
How about this
![image](https://github.com/Arcticons-Team/Icon-Request-Dashboard/assets/8929967/571ee14b-3b6e-4374-8ade-97c65248e83b)

**Comment by Donnnno** [comment]
Yeah, something like that should work!

**Comment by Kaiserdragon2** [comment]
i don't know how useful it would be to be able to select multiple entries at once
